### ISSUE TITLE
Examples of website organization

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [noaa-fisheries-integrated-toolbox/noaa-fisheries-integrated-toolbox.github.io#3]
@HaleyOleynik-NOAA I thought you could use an issue to track some of the available examples. Here are a few that I found.
- [Tidyverse](github.com/tidyverse)
- [Bioconductor](https://www.bioconductor.org/)
- [R-lib](https://github.com/r-lib)
- [rOpenGov](https://github.com/rOpenGov)
- [ROpenSci](https://github.com/ropensci) they had a "README.md" for their organization

[Awesome R organization](https://github.com/dirkschumacher/awesome-r-organizations) is a GitHub repository that lists a lot of great examples and it is actually how I found rOpenGov.

**Comment by k-doering-NOAA** [comment]
These are great, Kelli! I'm going to close this since it is info rather than an issue
